### ISSUE TITLE
overture/song-server: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/roadmap#104]
- [x] Update Jenkins pipeline to push image into ghcr
- [x] Make image public
- [x] Update helm chart to use image from ghcr
- [x] Merge Jenkins pipeline into release
- [x] Execute pipeline after merging all changes and confirm none of the pipeline steps are failing (Overture QA/STAGING helm redeployment involved)
- [ ] Communicate changes with RDPC team
- SONG Overture QA (pipeline)
- SONG Overture Staging (pipeline)
- SONG RDPC DEV
- intermediate SONG RDPC DEV
- submission SONG RDPC DEV
- SONG RDPC QA
- intermediate SONG RDPC QA
- submission SONG RDPC QA
- SONG RDPC PROD
- intermediate SONG RDPC PROD
- submission SONG RDPC PROD
- [ ] Communicate changes with CANCOGEN team
- SONG Cancogen DEV
- SONG Cancogen PROD

**Comment by yalturmes** [comment]
Separate tickets were created for tracking redeployment of SONG in RDPC and CANCOGEN envs.
- https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/roadmap/812
- https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/cancogen-virus-seq/roadmap/25
Closing ticket.
