### ISSUE TITLE
overture / arranger-test: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/roadmap#108]

**Comment by yalturmes** [comment]
This docker image is part of the arranger pipeline. However I don't see any anything in the pipeline that pushes this image into the registry. If I understand things right, this image is built and used locally within the pipeline for testing code. And if that's the case - we don't need to migrate it and ticket may be closed.
It's a good idea to validate this with somebody who understands more about arranger.
@akachru-github @joneubank - please advise.
