### ISSUE TITLE
overture.bio Privacy page links

### ISSUE THREAD

**Issue by kcullion** [overture-stack/roadmap#119]
On this page, https://www.overture.bio/privacy/

Please fix the following links at bottom of page:

- [ ] "organizational Privacy Policy" goes to https://oicr.on.ca/oicr-policies-and-procedures/
- [ ] "Information Practices Frequently Asked Questions" goes to https://oicr.on.ca/information-practices-frequently-asked-questions/

**Comment by samrichca** [comment]
https://5ff63dbeb61d545878cc1439--overture.netlify.app/privacy/

**Comment by b-f-chan** [comment]
Tested at netlify above, links are now correct
