### ISSUE TITLE
Research: GA4GH Passport integration for Overture

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/roadmap#139]
Will work with Melanie, Brandon and Christina to define the direction on this. 

Goals
- Understand what the integration will be
- How this translates to Ego data model
- Identify the outcome of this integration. 

From the grant proposal for reference: 

_Aim 2.1 Implement GA4GH Passport in Overture. The GA4GH Passport system is an integrated set of standards for managing researcher identity, authorization and access permissions for controlled-tier genomic data. Passport defines a standard format to transport a researcher’s digital identity and permissions to access dataset(s), as Fig. 4 illustrates. When researchers apply for dataset access, their research plan and intended use of the data are typically reviewed by a Data Access Committee (DAC) at, for example, dbGaP, EGA or ICGC. If granted access, these institutions will issue a Passport Visa. Passport Brokers will package visas, possibly from multiple issuers, into the researcher’s passport. The Passport Clearinghouse, the data hoster, reviews visas to decide whether to grant access to the datasets. Any Clearinghouse will need to support multiple Passport Brokers and visas from different Issuers in order for researchers to access datasets owned by different institutions.
We will add GA4GH passport functionality to Ego to serve as a Passport Broker. This will allow Ego to issue GA4GH compliant passports to authenticated users, and for Ego to collect passport visas from various issuers. To achieve this, we will extend Ego to conform to the requirements outlined by the GA4GH AAI specification. Similar passport broker will be the NIH Research Auth Service (RAS). To support Passport Clearinghouse functionality, we will enhance Score to consume and validate GA4GH visas. If, during the design phase we determine that Clearinghouse functionality does not mesh well with Score’s architecture, we will implement a separate Clearinghouse module and modify Score to call it to determine access permissions._

**Comment by akachru-github** [comment]
https://wiki.oicr.on.ca/display/OV/Investigation+-+Ga4gh+passports+in+Ego

**Comment by blabadi** [comment]
For the goals:
- Understand what the integration will be 
Ego would be a claim clearing house, this is described in details in the wiki in Atul's comment above
-  How this translates to Ego data model
changes to ego data model added to the wiki
- outcome of this integration 
new version of ego where it can be a clearing house i.e. consumer of passports from external ga4gh brokers and it can translate those visas into the ego's current permissions framework
