### ISSUE TITLE
Setup Dev & QA for Overture Development

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/roadmap#145]
Need DevOps to help setup a Dev and QA environment for development and testing of Overture features for ITCR

The previous environment is on Collab and will go away once Collab is decommissioned; hence we need a new one

What needs to be installed:

- [ ] Full DMS deploy with latest versions of componets, of specific importance are: Score, DMS-UI

**Comment by Buwujiu** [comment]
Dev passport is setup, this is enough for now, so will not set up QA overture.

**Comment by b-f-chan** [comment]
Completed, closing
