### ISSUE TITLE
Upgrade DMS UI to Use Arranger 3.x

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/roadmap#147]
Need to upgrade the DMS to use the latest Arranger 3.x version which has the table support needed for the J-Browse integration

Additionally, some quality-of-life UX enhancements requested (e.g. expand all, collapse all, scroll to top, for the filter control panel) need to be added into Arranger 3.0 itself, so this upgrade is needed

**Comment by b-f-chan** [comment]
Check with @justincorrigible if this is already upgraded in Overture QA

**Comment by justincorrigible** [comment]
Overture QA indeed runs Arranger 3 (with a compatible version of DMS-UI.

note: DMS itself (the installer script, etc.) hasn't been updated yet, but it's not clear whether that's in the scope of this ticket or not.

**Comment by b-f-chan** [comment]
Closing, already in develop branch
