### ISSUE TITLE
Setup Overture Sandbox

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/roadmap#149]
Setup an Overture sandbox for people who are interested in Overture to play around with

This would also be useful for whenever we do demos, conferences, roadshows, etc

Assigning @mcourtot for now to take up with DevOps team (cc: @puneet-oicr @MitchellShiell @justincorrigible)

**Team to discuss/collaborate on specific details/requirements of what will be setup**

**Comment by justincorrigible** [comment]
👍 Great!
