### ISSUE TITLE
Spike: Guided Installer- Technical Spec and Architecture

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#41]
## Objective
This will be a technical spec which will help in understanding the complexity of the architecture.

Expected Outcome, will be the following diagrams:
- [ ] sequence
- [ ] state
- [ ] process 

## Link for GoogleSheet
This shows how the guided insteller will look like for the end user:
https://docs.google.com/spreadsheets/d/1lGgjcmmZDZKYd6kMjO_UZJyAwp62BBnUgh26soTD24Y/edit#gid=15213591

## Outcome:

- [ ] Wiki page which outlines the high level architecture.

- [ ] Overview for the docker client.

**Comment by gokul472** [comment]
Moving to Sprint 3

**Comment by rtisma** [comment]
Please refer to the wiki page for the technical specification: https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs
