### ISSUE TITLE
Spike: To analyze how the publicly accessible DMS can be set up?

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#43]
Expected Outcome

- [ ] how the publicly accessible DMS can be set up? Is this even feasible to do?
- [ ] What level the automation can be done for the networking resources without compromising security?

**Comment by gokul472** [comment]
@rtisma @rosibaj : The spike has been created.

**Comment by b-f-chan** [comment]
Closing, already implemented and documented.  Enhancements to the process will be done separately under different projects.
