### ISSUE TITLE
ORCID: Spike -  How EGO can be architected to work with ORCID API

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#44]
**Problem**: For EGO, it is important to have the email address to be stored for the users. The public API returns the user ID and email, but there is certain change in settings which needs to be updated by the user.

Few Suggestions are as follows:
- [ ] Prompt users to change email access settings in ORCID and make it public, so that the Public API can work correctly. This will sometimes result in errors we need to deal with.
- [ ] Use the paid version with more application permissions that does not always have this issue. 
- [ ] Come up with an application solution that does not require email to be stored in EGO (since we can easily get the UserID from the API)
- [ ] Do we need to store the identity provider in Ego?

**Expected Outcome**
Ego will be able to work with ORCID API

**Comment by gokul472** [comment]
This will go to the Sprint 4

**Comment by b-f-chan** [comment]
Closing, won't do.  Ticket is old and no longer relevant based on the proper ORCID solution we have implemented.
