### ISSUE TITLE
Docs Site: Header & Footer

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/roadmap#45]
Work with the gatsby templates to make a product documentation page template.  The features include: 

- [ ] Product header (ask Kim for icons for each product)
- [ ] A link will always appear at the top of the left sidebar "Documentation Overview" that takes the user back to the documentation landing page
- [ ] Previous/Next links at the bottom of the page that make it easy for the user to go from page to page

WIKI page for more details:
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=OV&title=UI+Specifications+for+the+Overture+Documentation+Site

**Zeplin Link:** https://zpl.io/bl5pK15

<img width="1078" alt="2020-08-10_12-22-10" src="https://user-images.githubusercontent.com/18424138/89805787-28dac700-db04-11ea-923b-1199d9315119.png">

<img width="619" alt="2020-07-31_1139" src="https://user-images.githubusercontent.com/18424138/89051638-8e6bce00-d322-11ea-8b38-b91c1e591046.png">

**Comment by samrichca** [comment]
suggested scope change: only do the header & footer. do sidebars & search in other tickets (which have already been made)

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/6e04ae89-219e-4f5c-9e83-bba009ae6e9a)

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/4377f301-143a-4a00-8784-a0704eec7996)

**Comment by b-f-chan** [comment]
Change original description to meet modified scope

**Comment by samrichca** [comment]
mobile mockup from @kcullion 

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/8afdd76c-bc0f-47eb-adc5-cc176c14e82d)

**Comment by samrichca** [comment]
https://5fa1dc07e2ac75124c2c8ff6--overture.netlify.app/documentation/song/subsection-1

https://github.com/overture-stack/website/pull/93

**Comment by kcullion** [comment]
looks good @samrichca. I assume the search box and the back to docs landing page link will be styled in another ticket?

Just some font feedback - it's looking big to me in the browser
![image](https://user-images.githubusercontent.com/18424138/98120245-b3b92c80-1e7b-11eb-8eb2-ddf27ce8be58.png)

**Comment by samrichca** [comment]
@kcullion yeah, search box & documentation overview link will be in other tickets.

I reduced the font size a bit, does this look ok? 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/3540896/98128116-7d80aa80-1e85-11eb-92c7-03a583981161.png">

**Comment by kcullion** [comment]
yes @samrichca , thanks so much!

**Comment by rosibaj** [comment]
@samrichca whats the latest netlify link with the smaller text?

**Comment by rosibaj** [comment]
@samrichca one issue: 

![image](https://user-images.githubusercontent.com/15824252/98132662-aeafa980-1e8a-11eb-89a7-4bb5dbb5c2e8.png)

In this case (when ther eis content, but not a full page worth), the footer should just be at the bottom of the page, and the <last next> links at the bottom of the content the way  they are now.

**Comment by samrichca** [comment]
@kcullion @rosibaj updated netlify link

https://5fa2d53f1baa401467a93d56--overture.netlify.app/documentation/song/subsection-1

the sidebar columns... are gonna get ripped out shortly so I'm not gonna worry about making them full height for now

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/3e55cde8-64cf-4ed1-af2d-41dbb5d24208)

**Comment by rosibaj** [comment]
lgtm thanks @samrichca !
