### ISSUE TITLE
Docs site: Markdown styling

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#48]
This ticket refers to the various styling of the content on the site.

This includes the following:

Zeplin: https://zpl.io/bl5pK15

- [ ] **Headings**
<img width="567" alt="2020-07-31_1243" src="https://user-images.githubusercontent.com/18424138/89057322-6df44180-d32b-11ea-84ba-64f2ece24e81.png">

- [ ] **Code blocks**
Note: Ciaran said code themes can be customized, but either we can pick a predetermined theme or customize with overture colours: https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/themes/duotoneDark.js

Default copy icon:https://zpl.io/VOOk4o8
<img width="810" alt="Screen Shot 2020-08-10 at 12 16 03 PM" src="https://user-images.githubusercontent.com/18424138/89805256-5ffca880-db03-11ea-99f7-e3ff70bc85b4.png">

Hover over icon: https://zpl.io/bl5pK15
<img width="823" alt="Screen Shot 2020-08-10 at 12 16 18 PM" src="https://user-images.githubusercontent.com/18424138/89805285-6be86a80-db03-11ea-94d8-109f54880556.png">

Click to copy - will save code to clipboard and display "Copied!". This tooltip should fade out after approx. 3-5 seconds: https://zpl.io/2p9PLk8
<img width="825" alt="Screen Shot 2020-08-10 at 12 16 24 PM" src="https://user-images.githubusercontent.com/18424138/89805338-7c98e080-db03-11ea-8f0f-37489bd28674.png">

- [ ] **Custom box for an important content**
<img width="819" alt="2020-07-31_1237" src="https://user-images.githubusercontent.com/18424138/89056873-b8c18980-d32a-11ea-9eea-71fb51456ff3.png">

- [ ] **Image/screenshot with dropshadow**
<img width="811" alt="2020-07-31_12378" src="https://user-images.githubusercontent.com/18424138/89056908-cb3bc300-d32a-11ea-869c-a022fa5f7380.png">

Zeplin: https://zpl.io/2v4YjYn
- [ ] **Highlight for certain text**
![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/dd02cea9-0716-46e7-8dd0-994cabbfe863)

- [ ] **Tables**
<img width="820" alt="2020-07-31_1239" src="https://user-images.githubusercontent.com/18424138/89057069-0807ba00-d32b-11ea-9ab6-a10c1ddb6805.png">

Zeplin: https://zpl.io/VQwYJKn
- [ ] **Warning messages as shown in yellow background**.
![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/f8830f58-2c16-4110-83fc-596a8fe97187)

**Comment by samrichca** [comment]
investigation:
- there's a plugin for code highlighting (prismjs)
- no off-the-shelf copy/paste button for code highlighting sections in Gatsby/MDX, have to make this
- H# elements need to be customized so they're anchor tags for the right sidebar links
- warning & notes will be shortcodes or React components in Markdown, not sure
- images are easy to style
- backtick text is easy to style
- tables are easy to style

**Comment by samrichca** [comment]
https://5fab0e596ee0f412a627adbb--overture.netlify.app/documentation/song/markdown

known issues:
- not responsive when you resize the page
- when you click an anchor link to go somewhere else in the page, it's hidden by the navbar at the top
- right-hand table of contents doesn't work anymore
- on the pages with less content, the sidebars don't reach the footer

these will be resolved in the sidebars ticket

**Comment by samrichca** [comment]
https://github.com/overture-stack/website/pull/94

**Comment by b-f-chan** [comment]
Tested on netlify link above:

Successful:

- Header fonts/size/styling looks correct per Zeplin
- Code block styling looks correct per Zeplin (@kcullion are you OK with how the colour theme looks?)
- Important content box styling looks correct per Zeplin
- Text highlight styling looks correct per Zeplin
- Table styling looks correct per Zeplin
- Image with dropshadow looks correct per Zeplin
- Warning message styling looks correct per Zeplin

@kcullion can you please have a look as well to see if the styling is correct?  It looks good to me.

**Comment by kcullion** [comment]
@b-f-chan @samrichca 

This looks really great and will very helpful. Code blocks look great. Just talked to Sam about mentioning a bit about opening external links in new windows. 

Also, I find the horizontal rule a bit light. Sam can you change it to background-color:#DFDFE1; height:1px;

**Comment by kcullion** [comment]
As discussed with @samrichca in slack, there's a couple characters that got stripped out of the markdown:

- tables (colons aren't showing...and are the backslashes supposed to be in last column?)
![image (54)](https://user-images.githubusercontent.com/18424138/100650035-52b53500-3311-11eb-9d57-e8baf0a75348.png)

- horizontal rules, examples all look the same
![image (53)](https://user-images.githubusercontent.com/18424138/100650086-6a8cb900-3311-11eb-9f3e-c3f7a9377e3a.png)

**Comment by samrichca** [comment]
the current ticket/branch for this project is the sidebars one.

- external links are resolved in the sidebars ticket. I added a helper component that determines if a link is external or not, and adds target="_blank" to external links, or converts them to a Gatsby link if the URL is internal.
- will change HR colour.
- I'll update the markdown example to remove the info about colons and asterisks. These characters are being stripped out by the code formatting used in the project, which makes the examples a bit confusing.
- will make link colours higher-contrast shades of blue in warning & note boxes.

thanks @kcullion !
