### ISSUE TITLE
Overture environment clean up

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#51]
The Canarie project will be using the Overture QA environment to perform testing. It does not support migrations at the moment. 

Steps are as follows:
1) Editing the helm charts to standardize values
2) Can't start up ego because migrations were not run. Typically these are autorun.

**Comment by yalturmes** [comment]
Progress so far...
Re-deployed and configured following apps in overture:
* Ego overture qa
* Ego overture staging
* Song overture qa
* Song overture staging

**Comment by yalturmes** [comment]
Progress update:
Overture maestro and its dependencies (kafka and es-operator) have been deployed in dev and qa environment.

Closing notes notes:
Current state of overture apps configuration have been handed over to @rtisma as he will continue with overture applications setup.
