### ISSUE TITLE
NON-MVP Spike - Guided Installer-How to make the micro-services URL's to be publicly accessible?

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#54]
This ticket is NON-MVP for Canarie phase 1. This maybe  be implemented in phase 2.

The goal of this ticket is to find out, how to make the micro-services URL's (Song, Score, EGO) publicly accessible?

- [ ] The will allow users to work on the same DMS portal although they are present in various geo-graphical locations.

- [ ] Need to experiment with ssl-tunnels as a possibility for bypassing changes to networking. This would also allow a user to make services public WITHOUT needing to talk to I.T or logging into their router.

**Comment by gokul472** [comment]
This ticket is NON-MVP for Canarie phase 1. This maybe  be implemented in phase 2. Only high level recommendation can be provided on how to make the services publicly available.

**Comment by b-f-chan** [comment]
Duplicate, we have already implemented path-based proxy/gateway which will expose services via sub-paths from a registered domain over HTTPS

Closing
