### ISSUE TITLE
Doc Site: Finding the elements from the Gatsby link which suits our requirement

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#56]
- Finding the right elements/packages/plugins from the from the Gatsby which will help us to design the landing page

**Wiki link**
https://wiki.oicr.on.ca/display/OV/UI+Specifications+for+the+Overture+Documentation+Site

pls refer section 9 and 10 of this page for more details.

**Comment by samrichca** [comment]
updated spec with Gatsby links

**Comment by b-f-chan** [comment]
Reviewed with @samrichca - Since research is complete and we have the information (references/sources) to move forward.  Specifically for the homepage, we'll design starting with other sample pages in /src/pages (e.g. the Case Studies page, the About page, etc.).  Closing ticket.
