### ISSUE TITLE
Docs Site: Integrate Algolia search

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#57]
This ticket will help to integrate the search functionality using Algolia for the Canarie Doc site. The category of the pages is listed below:

The search functionality is present on the following pages:

1) Doc Site landing page

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/73e70b49-7d00-4607-a235-aee6da14360f)

2) Internal pages for the Doc site (Just shown one internal page as an example)

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/21965cfe-2cf7-4a01-9412-530d21723d6e)

**WIKI link**
https://wiki.oicr.on.ca/display/OV/UI+Specifications+for+the+Overture+Documentation+Site
 pls see section 9.0 of the wiki page for reference.

## Expected Outcome
The search functionality should be integrated with the doc site for all the required page.

## Dev task
API for searchhttps://www.algolia.com/doc/api-reference/widgets/search-box/js/

**Comment by samrichca** [comment]
gatsby + algolia is well documented: https://www.gatsbyjs.com/docs/adding-search-with-algolia/

**Comment by samrichca** [comment]
https://5fd138c2f466660e5754cdec--overture.netlify.app/documentation/

**Comment by b-f-chan** [comment]
Basic functionality and look and feel are good, we can refine & optimize the ranking later in a separate task

Closing
