### ISSUE TITLE
Docs Site: Search dropdown

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#58]
The goal of the ticket:
1) Ensuring the search dropdown window appears as the user is typing in the Keywords for their area of interest.
![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/952e46b2-c4d6-4732-8c73-6951e066c072)
2) In case, there are no results found for a specific keyword, the appropriate message is shown to the user. (shown in mockup)
![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/9d887dd3-e69a-43b0-a112-7825a35bfcc0)

3) Search drop down on the internal page
![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/f4e2511f-07a4-4f03-bcb0-52754348f375)

## Expected Outcome

- [ ] The search drop down window should show up. The keyword matching the search criteria should be highlighted in the search drop-down window.

- [ ] The error message to be shown in case, there are no search results for a specific keyword.

## Zeplin Links

- [ ] Default state: https://zpl.io/bLMOvyD
- [ ] Search results: https://zpl.io/Vkj51LL
- [ ] No results found: https://zpl.io/2jG43BQ
- [ ] Showing in an internal docs page: https://zpl.io/bJyqLKr

**Comment by b-f-chan** [comment]
Close as duplicate, tasks will be merged into #117
