### ISSUE TITLE
Guided installer: Some observations for the guided installer to be reported

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#59]
There are couple of issues to be reported for the Guided installer:

- [ ] Error while downloading the file: ERROR: Command error: Number of retries exhausted
Command: ./tools/score-client download --object-id 192011bc-76ff-5999-8e11-deef1ec16488 --output-dir /score-client/output/download1

Error: WARN: MD5 for /score-client/output/download1/192011bc-76ff-5999-8e11-deef1ec16488 was a9fd03670e7e46493bb95974294d4c4c but was expecting c03274816eb4907a92b8e5632cd6eb81
ERROR: Command error: Number of retries exhausted

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/58c00b15-5e56-4876-ac0b-19f4e08b3fbc)

- [ ] Make clean doesn't work: ERROR is : make: *** No rule to make target 'start-all-services'. Stop.
Command : make clean

Error: ERROR is : make: *** No rule to make target 'start-all-services'. Stop.

- [ ] Swagger doesn't recognize the Study_ID, although the study_ID=ABC123 exists
http://localhost:8080/swagger-ui.html#/Analysis/getAnalysisUsingGET

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/4654cf9c-c11a-4d9d-aedd-31ba6a8913a5)

- [ ] The URL for the ARRANGER portal: localhost:9080, Error : the site cannot be reached..

![image.png](https://images.zenhubusercontent.com/5ec563ba889df3e7a41572b3/f60dfc80-669d-4842-a5d2-8bd347f7f9da)

**Comment by gokul472** [comment]
Develop some components for the local host.
proxy the every single object URL.

**Comment by rosibaj** [comment]
@b-f-chan is this ticket sill valid?

**Comment by b-f-chan** [comment]
I never encountered this issue in my testing, let's close for now and we can re-open later if observed.
