### ISSUE TITLE
Guided Installer: Configuration of the Domain and IP of portal

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#67]
## Objective:
The user will have the option to configure the portal for both local and public usage.

## Pre Req:
In case of making the DMS portal publicly facing. It will be ADMIN's responsibility to configure the following:
a) The machine on which the DMS portal has been installed should be public facing.
b) It will be ADMIN's responsibility to ensure to provide us with the correct domain name which can be made public facing.
Link to the doc site will be provided [TBD]

## Acceptance Criteria
In order to achieve, the user should be prompted to get:
- [ ] Informed message to introduce the user to the public network setup:
"The Overture DMS can be configured to run in a local configuration or a public configuration. 
- In a local deployment, the DMS will only be accessible from the VM that the DMS is installed on.  
- In a public deployment, the DMS will be accessible via a web URL. You can either make URL's available either within or outside your organization. For more information on the domain/network setup, please see documentation: overture.bio/documentation/DMS/Network-Requirements"

- [ ] Prompt user to select public vs private network
- [ ] Prompt user to the path to upload the valid certificates
- [ ] Input the domain name.
- [ ] Input the IP for the network
- [ ] Ensure that the job will run every 3 months in the docker environment and is capable of automatically generating the valid certificates
- [ ] The list of the ports which needs to be open for the public interface of the portal will be provided to the DMS ADMIN.

## Dev tasks

**Comment by b-f-chan** [comment]
Duplicate, we have already implemented this in the path-based proxy/gateway in server mode, it requires a domain to be setup and provided, then services are accessible as sub-paths off that domain over HTTPS

Closing
