### ISSUE TITLE
Guided Installer: Registering of the Service provider with the DMS portal

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#73]
## Objective
The objective of this ticket is to register the service provider selected by the DMS Admin with the portal while installation.

## Pre-Req
There will be a link provided to the ADMIN to educate them as how to enter the information for various SSO methods.

## Details
The idea is to get the following information to register the service provider with EGO 
>>client_Id
>>client_secret
>>redirect_uri

## Acceptance Criteria

- [ ] The service providers are registered with the EGO with the required information as stated above.

**Comment by b-f-chan** [comment]
Closing as duplicate, provider setup is already implemented, and re-direct URI config will be done in dms#9
