### ISSUE TITLE
ORICD API: Technical system setup for ORCID API to work

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#76]
## Objective:
There needs to some system set up steps to be completed for the ORCID API implementation.

## Dev tasks
- [ ] able to accept and store ORCID iDs together with the user’s information.
- [ ] accepting and storing persistent access tokens together with the user’s account data.
- [ ] store all of the token response, including refresh tokens, scopes, and token expiry.
- [ ] record both calls made to the ORCID API and responses received so that the logs can be retrieved at later stage if needed.

**Comment by b-f-chan** [comment]
Closing, won't do.  Ticket is old and no longer relevant based on the proper ORCID solution we have implemented.
