### ISSUE TITLE
Guided Installer: Tracking the unique user downloads of the DMS portal.

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#77]
Refer to https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs#DMSInstallerTechnicalSpecs-TrackingUserDownloads

## Objective
The objective of this ticket is to keep the track of the number of the unique users who have downloaded the DMS portal on their machine.

**Comment by b-f-chan** [comment]
Closing, we will take this up as a new sub-task in the ITCR project, which has an entire objective for various metrics tracking (this is only one of them).
