### ISSUE TITLE
Portal - Routing set up for the login page

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#78]
## Objective
The purpose of this ticket is to set up the routing.

## Dev task

- [ ] setting up routing to either with nextjs.
- [ ] set up routes for repository and login pages. For home page, it needs to be discussed.

**Comment by b-f-chan** [comment]
Note: to merge work with #60

**Comment by b-f-chan** [comment]
Merged task into #60 per discussion with @anncatton, closing as duplicate
