### ISSUE TITLE
Add CI/CD for DMS Portal

### ISSUE THREAD

**Issue by rtisma** [overture-stack/roadmap#80]
- [ ] create helm chart
- [ ] create overture-infra values for portal
- [ ] create jenkinsfile
- [ ] auto deploy using Jenkins for QA and Staging.
- [ ] test

This will set up for QA and staging env.

**Comment by gokul472** [comment]
This will not block the DEV work.

**Comment by gokul472** [comment]
This will be blocker ticket in future for QA and Demo purposes. This will be re-visited when some DEV work on DMS portal is completed.

**Comment by akachru-github** [comment]
@gokul472  / @anncatton , will Arranger be required in the Overture env for this portal to work?
cc. @yalturmes

**Comment by anncatton** [comment]
Yeah we'll need Arranger so the portal has a backend to talk to

**Comment by gokul472** [comment]
@akachru-github - As per my understanding, Arranger is important for the DMSPORTAL.

**Comment by akachru-github** [comment]
Thanks!
We are prioritizing work for Devops on some blocking issues at the moment, so minimally, if we had Arranger deployed to the QA environment, would you **manually** be able to deploy the DMS portal until we get to this ticket for the CI CD work for automated deploys?

At least we can unblock deployment and testing to start.

**Comment by anncatton** [comment]
Well right now there's nothing to deploy, and likely won't be until I'm back the week after next. But I think we need something set up, so the portal has a target in dockerhub etc. Right now the Portal does not exist at all from that perspective.

**Comment by b-f-chan** [comment]
Discussed with @anncatton this was already completed and can be closed.
