### ISSUE TITLE
Review DMS Installer Tech Spec 

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/roadmap#85]
Review the DMS Installer tech spec & provide @rtisma prior to sprint planning (before Sept 17, 2020):
https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs

The entire spec will require review, but In particular, we need guidance on the selection of which of 3 proposed solutions to track the unique user downloads.

**Comment by andricDu** [comment]
Provided feedback. Overall looks good.
