### ISSUE TITLE
Implement Client Credentials Flow b/w SONG and SCORE 

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/roadmap#90]
Implement Communication Flow B/w SONG and SCORE 
- there is an api key in the application yaml that is used to pass 
- this is a user api-key

https://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/client/OAuth2RestTemplate.html

- song talks to score via api keys. 
- we need to change that so song retrieves a JWT from ego, and then uses that to talk to score.
- we do not forward the users JWT.
-  in order for song to check if an object exists in score, song calls the /upload/<objectId> endpoint on score (this is called during the /publish endpoint for song), which returns true if the object exists, and false otherwise. 
- That score endpoint requires score.WRITE scope. If a user only has song.WRITE scope, they can call the /publish endpoint on song but not the /upload/<objectId> endpoint on score. 
- For this reason, forwarding a user token is does not work, and song needs to use its own, application level, token

**Comment by rtisma** [comment]
https://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/client/OAuth2RestTemplate.html
