### ISSUE TITLE
Cleanup overture-qa/overture-staging env

### ISSUE THREAD

**Issue by rtisma** [overture-stack/roadmap#91]
There are several unused deployments in both overture-qa and overture-staging, that have been failing for over a year, or that are outdated (helm2). In order to clean these up, their corresponding Jenkins pipeline must also be cleaned up. Whatever is left over can be manually deleted.

This is not critical, but important we keep things clean.

**Comment by b-f-chan** [comment]
@yalturmes - Not a high priority, but when one of you have a chance, could you just see if this old ticket from Rob is still true?

Perhaps the old deployments in QA and Staging have already been cleaned up in the pipeline.  I'm not sure what exactly he is referring to, but maybe a quick check can verify that there is no "junk" left and we can close this.  Or we need to keep open and cleanup.  Thanks!

**Comment by yalturmes** [comment]
Env clean-up - no longer relevant.
Jenkins pipeline clean-up is already planned and will be taken care of in scope of migration to new JCasC Jenkins instances.
Closing ticket.
