### ISSUE TITLE
Minor Fixes for Overture.bio Mobile Version

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/roadmap#94]
The mobile version of the Overture.bio site has some fixes required to make it more mobile-friendly.

This was reviewed on latest netlify link for #46

![overture-mobile1.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/1cfe5b78-27ca-400d-b2bc-4f4be3d592a9)

![overture-mobile2.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/67df64bf-515c-4caa-8ac2-6d4ec5520822)

**Comment by samrichca** [comment]
credits at the bottom:

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/0903db7a-3e54-474e-a53a-8b3aa7fc48a6)
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/f12a0341-af85-4530-ac51-c876a1bca4dd)

removed horizontal padding on mobile footer links
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/77ed5a47-28fa-48c2-b5c3-7ac1f2e94208)

magenta link in mobile menu 
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/787440dd-76ba-47a9-8d48-ef173c1a4733)

vertical links under DMS Bundle
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/4ebf7964-7cb1-4c9c-8bfe-3008fd225efd)

**Comment by samrichca** [comment]
https://5f9b05d0a9b23c35267399b8--overture.netlify.app/
https://github.com/overture-stack/website/pull/90

**Comment by kcullion** [comment]
this looks great, thanks @samrichca

**Comment by rosibaj** [comment]
lgtm. thanks @samrichca
